# Generated by Django 5.1.6 on 2025-02-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='autho',
            new_name='author',
        ),
    ]
